### ISSUE TITLE
ошибка миграции

### ISSUE THREAD

**Issue by latishev** [Pshatsillo/mega_hacs#2]
**Описание**
Миграцию выполнял по совету 
https://ab-log.ru/forum/viewtopic.php?f=1&t=1788&start=880

> Есть еще один способ, через UI HA. Может для кого-то будет проще/удобней)
> Идем в HACS, в верхнем правом углу жмем иконку "три точки" и выбираем "Пользовательские репозитории" - нажимаем.
> Откроется окно для добавления репозитория. Адрес репозитория указываем https://github.com/Pshatsillo/mega_hacs, тип - интеграция. Добавляем.
> Далее почти как обычно - в фильтрах пишем mega, видим два репозитория MegaD. Выбираем у которого активность свежее и нажимаем скачать.
> Готово.

**Версии систем**
Enviroment: raspberry
HA version: 2024.11.1
mega_hacs version: 
megad firmware version: последние
используется mqtt: false

**LOG**
Регистратор: homeassistant.config_entries
Источник: config_entries.py:978
Первое сообщение: 02:04:43 (3 сообщений)
Последнее сообщение: 02:04:44

Error migrating entry 203 for mega
Error migrating entry 201 for mega
Error migrating entry 202 for mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/__init__.py", line 268, in async_migrate_entry
    await async_update_entry(hass, config_entry)
  File "/config/custom_components/mega/__init__.py", line 284, in async_update_entry
    config_entry.data = new
    ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 463, in __setattr__
    raise AttributeError(
AttributeError: data cannot be changed directly, use async_update_entry instead

**Comment by ilyasor** [comment]
Подтверждаю проблему

**Comment by Pshatsillo** [comment]
Переписал всё под требования HASS, перепробовал все варианты у себя. Никаких ошибок. Если опять что-то не так пойдёт, предлагаю попробовать удалить предыдущую интеграцию и установить мою. Сейчас у меня запуск без единого предупреждения. Устанавливал через custom repository в HACS

**Comment by ilyasor** [comment]
> Переписал всё под требования HASS, перепробовал все варианты у себя. Никаких ошибок. Если опять что-то не так пойдёт, предлагаю попробовать удалить предыдущую интеграцию и установить мою. Сейчас у меня запуск без единого предупреждения. Устанавливал через custom repository в HACS

Все завелось, большое спасибо!
